USE [master]
GO

/****** Object:  Database [QLTNDT]    Script Date: 30-Jan-24 1:21:43 AM ******/
CREATE DATABASE [QLTNDT]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'QLTNDT', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SERVER\MSSQL\DATA\QLTNDT.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'QLTNDT_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SERVER\MSSQL\DATA\QLTNDT_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [QLTNDT].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [QLTNDT] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [QLTNDT] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [QLTNDT] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [QLTNDT] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [QLTNDT] SET ARITHABORT OFF 
GO

ALTER DATABASE [QLTNDT] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [QLTNDT] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [QLTNDT] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [QLTNDT] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [QLTNDT] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [QLTNDT] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [QLTNDT] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [QLTNDT] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [QLTNDT] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [QLTNDT] SET  DISABLE_BROKER 
GO

ALTER DATABASE [QLTNDT] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [QLTNDT] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [QLTNDT] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [QLTNDT] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [QLTNDT] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [QLTNDT] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [QLTNDT] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [QLTNDT] SET RECOVERY FULL 
GO

ALTER DATABASE [QLTNDT] SET  MULTI_USER 
GO

ALTER DATABASE [QLTNDT] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [QLTNDT] SET DB_CHAINING OFF 
GO

ALTER DATABASE [QLTNDT] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [QLTNDT] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [QLTNDT] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [QLTNDT] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [QLTNDT] SET QUERY_STORE = OFF
GO

ALTER DATABASE [QLTNDT] SET  READ_WRITE 
GO


